# Generated by Django 3.2.17 on 2023-08-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='reblog',
            field=models.BooleanField(default=False, help_text='Reblogged post.', verbose_name='Reblog'),
        ),
        migrations.AddField(
            model_name='entry',
            name='reblog_by',
            field=models.CharField(blank=True, max_length=64, verbose_name='Reblogged by'),
        ),
        migrations.AddField(
            model_name='entry',
            name='reblog_uri',
            field=models.CharField(blank=True, max_length=128, verbose_name='Reblogged URI'),
        ),
        migrations.AddField(
            model_name='service',
            name='user_id',
            field=models.CharField(blank=True, help_text='Optional User ID', max_length=64, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
