# Generated by Django 4.2.7 on 2024-01-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_reblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='skip_reblogs',
            field=models.BooleanField(default=False, help_text='Skip importing reblogged posts.', verbose_name='Skip reblogs'),
        ),
        migrations.AlterField(
            model_name='service',
            name='api',
            field=models.CharField(choices=[('selfposts', 'Self Posts'), ('webfeed', 'Webfeed'), ('mastodon', 'Mastodon'), ('pixelfed', 'PixelFed'), ('flickr', 'Flickr'), ('twitter', 'Twitter'), ('vimeo', 'Vimeo'), ('youtube', 'YouTube')], db_index=True, default='feed', max_length=16, verbose_name='API'),
        ),
    ]
