# Generated by Django 4.2.7 on 2024-01-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_skip_reblogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pshb',
            new_name='WebSub',
        ),
    ]
