# Generated by Django 5.2.12 on 2026-03-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stream', '0005_alter_service_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='api',
            field=models.CharField(
                choices=[
                    ('selfposts', 'Self Posts'),
                    ('webfeed', 'Webfeed'),
                    ('mastodon', 'Mastodon'),
                    ('atproto', 'AT Protocol'),
                    ('pixelfed', 'PixelFed'),
                    ('flickr', 'Flickr'),
                    ('twitter', 'Twitter'),
                    ('vimeo', 'Vimeo'),
                    ('youtube', 'YouTube'),
                ],
                db_index=True,
                default='feed',
                max_length=16,
                verbose_name='API',
            ),
        ),
    ]
