# Generated by Django 6.1.1 on 2026-09-23 11:40

import glifestream.stream.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stream', '0009_servicefetchstate_failure_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=glifestream.stream.models.upload_path),
        ),
    ]
