# Generated by Django 6.1.1 on 2026-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stream', '0010_media_random_upload_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='service',
            name='api',
            field=models.CharField(
                choices=[
                    ('selfposts', 'Self Posts'),
                    ('webfeed', 'Webfeed'),
                    ('mastodon', 'Mastodon'),
                    ('atproto', 'AT Protocol'),
                    ('pixelfed', 'PixelFed'),
                    ('github', 'GitHub'),
                    ('flickr', 'Flickr'),
                    ('twitter', 'Twitter'),
                    ('vimeo', 'Vimeo'),
                    ('youtube', 'YouTube'),
                ],
                db_index=True,
                default='feed',
                max_length=16,
                verbose_name='API',
            ),
        ),
    ]
