# Generated by Django 6.1.1 on 2026-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stream', '0011_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public',
            field=models.BooleanField(
                default=False,
                help_text='Public services are visible to anyone.',
                verbose_name='Public',
            ),
        ),
    ]
