# Generated by Django 6.1.1 on 2026-09-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stream', '0013_websub_hub_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSubPublishRequest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'requested_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Requested at'
                    ),
                ),
            ],
            options={
                'verbose_name': 'WebSub publish request',
            },
        ),
    ]
