# Generated by Django 6.1.1 on 2026-10-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stream', '0014_websubpublishrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryUpgrade',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('upgrader', models.CharField(max_length=32, verbose_name='Upgrader')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('applied', 'Applied'),
                            ('skipped', 'Skipped'),
                            ('reverted', 'Reverted'),
                        ],
                        max_length=16,
                        verbose_name='Status',
                    ),
                ),
                (
                    'old_content',
                    models.TextField(blank=True, verbose_name='Old contents'),
                ),
                (
                    'old_link',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='Old link'
                    ),
                ),
                (
                    'old_mblob',
                    models.TextField(blank=True, null=True, verbose_name='Old media'),
                ),
                (
                    'new_content',
                    models.TextField(blank=True, verbose_name='New contents'),
                ),
                (
                    'new_link',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='New link'
                    ),
                ),
                (
                    'new_mblob',
                    models.TextField(blank=True, null=True, verbose_name='New media'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
                ),
                (
                    'reverted_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Reverted at'
                    ),
                ),
                (
                    'entry',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='upgrades',
                        to='stream.entry',
                        verbose_name='Entry',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Entry upgrade',
                'verbose_name_plural': 'Entry upgrades',
                'ordering': ('-created_at', '-id'),
                'indexes': [
                    models.Index(
                        fields=['upgrader', 'status'],
                        name='stream_entr_upgrade_446c4f_idx',
                    )
                ],
            },
        ),
    ]
