# Generated by Django 6.1.1 on 2026-10-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stream', '0015_entryupgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryupgrade',
            name='batch',
            field=models.CharField(
                blank=True, db_index=True, max_length=32, verbose_name='Batch'
            ),
        ),
    ]
