version: "3"

services:
  app:
    image: ${APP_IMAGE:-ghcr.io/wojciechpolak/glifestream:latest}
    restart: unless-stopped
    build: .
    volumes:
        - app_static:/app/static
        - ${RUN_DIR:-./run}:/app/run
        - ${RUN_DIR_MEDIA:-./run/media}:/app/media
    environment:
        - VIRTUAL_HOST=${VIRTUAL_HOST:-}
        - VIRTUAL_PATH=${VIRTUAL_PATH:-/}
        - APP_SECRET_KEY
    depends_on:
        - memcached
  nginx:
      image: ${NGINX_IMAGE:-nginx:1.25}
      restart: unless-stopped
      volumes:
          - app_static:/app/static
          - ${RUN_DIR:-./run}:/app/run
          - ${RUN_DIR_MEDIA:-./run/media}:/app/media
          - ${NGINX_DIR_TEMPLATES:-./run/nginx/templates}:/etc/nginx/templates
      ports:
          - "${APP_PORT:-8080}:80"
      environment:
          - VIRTUAL_HOST=${VIRTUAL_HOST:-_}
          - VIRTUAL_PATH=${VIRTUAL_PATH:-/}
      depends_on:
          - app
  memcached:
      image: ${MEMCACHED_IMAGE:-memcached:1.6}
      restart: unless-stopped
      entrypoint:
          - memcached
          - -m ${MEMCACHED_SIZE:-2}

volumes:
  app_static:
