[tool.poetry]
name = "glifestream"
version = "0.1.0"
description = "A free lifestream platform and social activity reader"
authors = ["WAP"]

[tool.poetry.dependencies]
beautifulsoup4 = "4.11.1"
Django = "^4.2.6"
django-pipeline = "^2.0.9"
feedparser = "^6.0"
libsasscompiler = "0.1.8"
Markdown = "^2.6"
Pillow = "^10.0"
python = "^3.11"
requests-oauthlib = "^0.4"
uWSGI = "^2.0.21"
workerpool = "^0.9"
pymemcache = "^4.0.0"

[tool.poetry.dev-dependencies]
pylint = "3.0.1"
pytest = "7.1.2"
pytest-django = "^4.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
