# Generated by Django 6.1.1 on 2026-09-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gauth', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Interface language. Empty means the browser decides.',
                max_length=10,
                verbose_name='Language',
            ),
        ),
    ]
