# Generated by Django 6.1.1 on 2026-09-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gauth', '0003_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='token',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Token'
            ),
        ),
    ]
