# Generated by Django 6.1.1 on 2026-09-27 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gauth', '0004_oauthclient_longer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fold_lines',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Lines of an entry the timeline shows before "Show more". 0 never folds. Empty uses the site default.',
                null=True,
                validators=[django.core.validators.MaxValueValidator(500)],
                verbose_name='Fold long entries',
            ),
        ),
    ]
